services:
  - type: web
    name: rtp-m-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: FRONTEND_URL
        value: https://rtp-m-liart.vercel.app/ 
    buildFilter:
      paths:
        - backend/**